[package]
name = "mascate-affiliate"
description = "Affiliate: Programs, Affiliate Links, Conversions, Commissions and Payouts."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
