[package]
name = "mascate-commerce"
description = "Commerce: Listings, Orders, Purchase Orders and shipping on each Sales Channel."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
libsql.workspace = true
mascate-inventory.workspace = true
mascate-kernel.workspace = true
mascate-platform.workspace = true
rust_decimal.workspace = true
thiserror.workspace = true

[dev-dependencies]
futures.workspace = true
mascate-kernel = { workspace = true, features = ["test-support"] }
proptest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
